lab03/encuesta/urls.py
from django.urls import path

from . import views

app_name = 'encuesta'

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:pregunta_id>/',views.detalle,name='detalle'),
    path('<int:pregunta_id>/votar',views.votar,name='votar')
]

lab03/lab03/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab03/encuesta/models.py
from django.db import models

# Create your models here.
class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    

lab03/encuesta/views.py
from django.shortcuts import render

# Create your views here.
from .models import Opcion,Pregunta

# Create your views here.
def index(request):
    latest_question_list = Pregunta.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request,'encuesta/index.html',context)

lab03/templates/encuesta/cliente.html
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Clientes</title>
</head>
<body>
    <h1>Listado de Clientes</h1>
    <ul>
        {% for cliente in clientes %}
            <li>
                <strong>Código:</strong> {{ cliente.codigo }}<br>
                <strong>Nombre:</strong> {{ cliente.nombre }}<br>
                <strong>Dirección:</strong> {{ cliente.direccion }}<br>
                <strong>Teléfonos:</strong>
                <ul>
                    {% for telefono in cliente.telefonos.all %}
                        <li>{{ telefono.numero }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

lab03/templates/encuesta/detalle.html
<h1>{{ pregunta.pregunta_texto }}</h1>

<form action="{% url 'encuesta:votar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id}}">
        <label for="opcion{{forloop.counter }}">{{ opcion.opcion_texto }}</label><br>
    {% endfor %}
    <input type="submit" value="votar">
</form>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>

lab03/templates/encuesta/index.html
<h1>Encuesta</h1>
{% if latest_question_list %}
    <ul>
        {% for pregunta in latest_question_list %}
            <li>
                <a href="/encuesta/{{pregunta.id}}">
                    {{pregunta.pregunta_texto}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay registros</p>
{% endif %}

lab03/templates/encuesta/provedor.html
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Proveedores</title>
</head>
<body>
    <h1>Listado de Proveedores</h1>
    <ul>
        {% for proveedor in proveedores %}
            <li>
                <strong>Código:</strong> {{ proveedor.codigo }}<br>
                <strong>Nombre:</strong> {{ proveedor.nombre }}<br>
                <strong>Dirección:</strong> {{ proveedor.direccion }}<br>
                <strong>Teléfono:</strong> {{ proveedor.telefono }}<br>
                <strong>Página Web:</strong> {{ proveedor.pagina_web }}<br>
            </li>
        {% endfor %}
    </ul>
</body>
</html>